WHL/Models/Entity/Inventories/Inventory.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using Newtonsoft.Json;

using WHL.Models.Virtual;
using WHL.Models.Entity.Bases;
using WHL.Models.Entity.Stores;



namespace WHL.Models.Entity.Inventories
{
    /// <summary>
    /// Author: Pango
    /// 库存实体类： 放某个SKU的所有库存信息的主类。
    /// </summary>
    public class Inventory : BaseEntity
    {

        public int ProductID { get; set; }

        public int StoreID { get; set; }

        [LangDisplayName("Avail", ResourceName = "Inventory_Entity_Avail")]
        public int? Avail { get; set; }


        [LangDisplayName("SwAvail", ResourceName = "Inventory_Entity_SwAvail")]
        public int? SwAvail { get; set; }


        [LangDisplayName("OnIn", ResourceName = "Inventory_Entity_OnIn")]
        public int? OnIn { get; set; }


        [LangDisplayName("OnOut", ResourceName = "Inventory_Entity_OnOut")]
        public int? OnOut { get; set; }


        [LangDisplayName("InSum", ResourceName = "Inventory_Entity_InSum")]
        public int? InSum { get; set; }


        [LangDisplayName("OutSum", ResourceName = "Inventory_Entity_OutSum")]
        public int? OutSum { get; set; }

        [LangDisplayName("OnHold", ResourceName = "Inventory_Entity_OnHold")]
        public int? OnHold { get; set; }

        [LangDisplayName("DiffSum", ResourceName = "Inventory_Entity_DiffSum")]
        public int? DiffSum { get; set; }



        [LangDisplayName("ShipMiss", ResourceName = "Inventory_Entity_ShipMiss")]
        public int? ShipMiss { get; set; }



        public virtual Product Product { get; set; }

        public virtual Store Store { get; set; }

        [JsonIgnore]
        [NotMapped]
        public virtual int QueryAvail1 { get; set; }

        [JsonIgnore]
        [NotMapped]
        public virtual int QueryAvail2 { get; set; }

    }
}

WHL/Models/Entity/Inventories/InventoryLog.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

using WHL.Helpers;
using WHL.Models.Virtual;
using WHL.Models.Entity.Bases;
using WHL.Models.Entity.Deliveries;



namespace WHL.Models.Entity.Inventories
{
    /// <summary>
    /// Author: Pango
    /// 库存变更日志实体类：记录库存每次变化的发生来源，以及变化前后之数量。
    /// </summary>
    public class InventoryLog:BaseEntity
    {

        /// <summary>
        /// the constructor which easy to set the inv1 and inv2 data
        /// </summary>
        /// <param name="inv1"></param>
        /// <param name="inv2"></param>
        public InventoryLog(Inventory inv1,Inventory inv2) {
            
            this.Avail1 = inv1.Avail;
            this.Avail2 = inv2.Avail;

            this.OnHold1 = inv1.OnHold;
            this.OnHold2 = inv2.OnHold;

            this.InSum1 = inv1.InSum;
            this.InSum2 = inv2.InSum;

            this.OutSum1 = inv1.OutSum;
            this.OutSum2 = inv2.OutSum;

            this.OnIn1 = inv1.OnIn;
            this.OnIn2 = inv2.OnIn;

            this.OnOut1 = inv1.OnOut;
            this.OnOut2 = inv2.OnOut;

            this.swAvail1 = inv1.SwAvail;
            this.SwAvail2 = inv2.SwAvail;

            this.ShipMiss1 = inv1.ShipMiss;
            this.ShipMiss2 = inv2.ShipMiss;

            this.DiffSum1 = inv1.DiffSum;
            this.DiffSum2 = inv2.DiffSum;
        }


        // import or delivery or adjustment 
        public int ChangeType { get; set; }


        public int InventoryID { get; set; }

        public int? DeliveryLogID { get; set; }

        // 下面记录了改变前和改变后各样数值

        [LangDisplayName("From Avail", ResourceName = "Inventory_Entity_Log_Avail1")]
        public int? Avail1 { get; set; }

        [LangDisplayName("To Avail", ResourceName = "Inventory_Entity_Log_Avail2")]
        public int? Avail2 { get; set; }

        [LangDisplayName("From OnHold", ResourceName = "Inventory_Entity_Log_OnHold")]
        public int? OnHold1 { get; set; }

        [LangDisplayName("To OnHold", ResourceName = "Inventory_Entity_Log_OnHold2")]
        public int? OnHold2 { get; set; }


        [LangDisplayName("From SwAvail", ResourceName = "Inventory_Entity_Log_SwAvail1")]
        public int? swAvail1 { get; set; }

        [LangDisplayName("To SwAvail", ResourceName = "Inventory_Entity_Log_SwAvail2")]
        public int? SwAvail2 { get; set; }


        [LangDisplayName("From OnIn", ResourceName = "Inventory_Entity_Log_OnIn1")]
        public int? OnIn1 { get; set; }

        [LangDisplayName("To OnIn", ResourceName = "Inventory_Entity_Log_OnIn2")]
        public int? OnIn2 { get; set; }


        [LangDisplayName("From OnOut", ResourceName = "Inventory_Entity_Log_OnOut1")]
        public int? OnOut1 { get; set; }

        [LangDisplayName("To OnOut", ResourceName = "Inventory_Entity_Log_OnOut2")]
        public int? OnOut2 { get; set; }


        [LangDisplayName("From InSum", ResourceName = "Inventory_Entity_Log_InSum1")]
        public int? InSum1 { get; set; }

        [LangDisplayName("To InSum", ResourceName = "Inventory_Entity_Log_InSum2")]
        public int? InSum2 { get; set; }


        [LangDisplayName("From OutSum", ResourceName = "Inventory_Entity_Log_OutSum1")]
        public int? OutSum1 { get; set; }

        [LangDisplayName("To OutSum", ResourceName = "Inventory_Entity_Log_OutSum2")]
        public int? OutSum2 { get; set; }



        [LangDisplayName("From diffSum", ResourceName = "Inventory_Entity_Log_DiffSum1")]
        public int? DiffSum1 { get; set; }


        [LangDisplayName("To DiffSum", ResourceName = "Inventory_Entity_Log_DiffSum2")]
        public int? DiffSum2 { get; set; }



        [LangDisplayName("From ShipMiss", ResourceName = "Inventory_Entity_Log_ShipMiss1")]
        public int? ShipMiss1 { get; set; }

        [LangDisplayName("To ShipMiss", ResourceName = "Inventory_Entity_Log_ShipMiss2")]
        public int? ShipMiss2 { get; set; }


        public virtual Inventory Inventory { get; set; }

        public virtual DeliveryLog DeliveryLog{ get; set; }


        [LangDisplayName("Type", ResourceName = "Inventory_Entity_Log_ChangeType")]
        public string ChangeTypeLayout
        {
            get
            {
                return GetChangeTypeLayout(this.ChangeType);
            }
        }

        public static string GetChangeTypeLayout(int changeType)
        {
            switch (changeType)
            {
                case (int)InventoryLogTypeEnum.Delivery:
                    return LangHelper.Get("InventoryLog_Entity_Type_Enum_Delivery");          // 由货运单影响： Updated by Delivery
                case (int)InventoryLogTypeEnum.Adjustment:
                    return LangHelper.Get("InventoryLog_Entity_Type_Enum_Adjustment");        // 由库存调整影响:Updated by Adjustment
                case (int)InventoryLogTypeEnum.Import:
                    return LangHelper.Get("InventoryLog_Entity_Type_Enum_Import");            // 由导入影响：Updated by Import 
                default:
                    return "undefined";
            }
        }
    }



    /// <summary>
    /// Author: Pango
    /// 日志类型，记录造成变化的来源，包括： 货运，库存调整，导入
    /// </summary>
    public enum InventoryLogTypeEnum
    {
        Delivery = 1,
        Adjustment = 2,
        Import = 3
    }
}

WHL/Controllers/InventoryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.IO;
using System.Data.OleDb;

using WHL.Helpers;
using WHL.Services;

using WHL.Models.Virtual;
using WHL.Models.Entity.Inventories;
using WHL.Models.Entity.FileDatas;

namespace WHL.Controllers
{
    /// <summary>
    /// InventoryController：we put all inventory view controllers here
    /// </summary>
    public class InventoryController : BaseController
    {


        /// <summary>
        /// Query partial view page
        /// </summary>
        /// <returns></returns>
        public ActionResult Query()
        {
            
            return PartialView();
        }

        /// <summary>
        /// List partial view page
        /// </summary>
        /// <returns></returns>
        public ActionResult List()
        {
            return PartialView();
        }


        /// <summary>
        /// Get the inventory list result in jquery data table JSON format, return the DataTable Result with paging and sorting.
        /// </summary>
        /// <param name="dtParams">Jquery Data Table Parameter</param>
        /// <param name="queryInventory">Query Inventory Object</param>
        /// <returns>JSON: DataTable Result with paging and sorting</returns>
        public JsonNetResult GetInventoryDataTableJson(DTParams dtParams, Inventory queryInventory)
        {
            DTResult<Inventory> inventoryDataTableResult = inventoryService.GetInventoryDataTableResult(dtParams, queryInventory);
            return new JsonNetResult(inventoryDataTableResult);
        }


        // EXPORT: Export Inventory List
        public JsonNetResult ExportJson(FileData submitFileData,Inventory eff)
        {
            JsonNetPackResult packResult = null;
            packResult = inventoryService.Export(submitFileData, eff);
            return new JsonNetResult(packResult);
        }

        /// <summary>
        /// Json upload an excel file and import to db
        /// </summary>
        /// <param name="uploadFile">the excel upload file</param>
        /// <param name="mapRule">the map rule of import</param>
        /// <returns></returns>
        public JsonNetResult ImportJson(FileData submitFileData, int eff)
        {
            JsonNetPackResult packResult = inventoryService.Import(submitFileData,eff);
            return new JsonNetResult(packResult);
        }

        /// <summary>
        /// close the database
        /// </summary>
        /// <param name="disposing"></param>
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                inventoryService.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WHL/Controllers/ModalController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.IO;

using WHL.Services;
using WHL.Models.Virtual;


namespace WHL.Controllers
{
    /// <summary>
    /// ModalController: we put all modals(pop up partial view) here.
    /// </summary>
    public class ModalController : BaseController
    {
        /// <summary>
        /// Outbound popup partial view.
        /// </summary>
        /// <returns></returns>
        public ActionResult Outbound()
        {
            return PartialView();
        }
        public ActionResult Import()
        {
            return PartialView();
        }

        public ActionResult Export()
        {
            return PartialView();
        }

        public ActionResult Inbound()
        {
            return PartialView();
        }

        public ActionResult Epacket() {
            return PartialView();
        }

    }
}

WHL/Views/Inventory/Index.cshtml
@Scripts.Render("~/Scripts/Common/jqueryTable")
@Styles.Render("~/Styles/Common/jqueryTable")
@Scripts.Render("~/Scripts/WHL/inventory")
@Scripts.Render("~/Scripts/WHL/outbound")
@Scripts.Render("~/Scripts/WHL/inbound")
@Scripts.Render("~/Scripts/WHL/import")
@Scripts.Render("~/Scripts/WHL/export")
@Scripts.Render("~/Scripts/WHL/epacket")

<!--we put index content here-->
<div style="min-height:100%"  align="left">
    <ul style="list-style: none; text-align: left; margin: 5px; padding: 5px; " >
        <li style="float:left;width:15%;" >
           @{Html.RenderAction("Query");}
        </li>
        <li style="float: left; width: 85%">
           @{Html.RenderAction("List");}
        </li>
    </ul>
</div>

<!--we put all hidden popup modals here!-->
<div  id="modals">
    @{Html.RenderAction("Outbound","Modal");}
    @{Html.RenderAction("Inbound", "Modal");}
    @{Html.RenderAction("Import", "Modal");}
    @{Html.RenderAction("Export", "Modal");}
    @{Html.RenderAction("Epacket", "Modal");}
</div>

WHL/Views/Inventory/List.cshtml
@model IEnumerable<Inventory>
<div class="container">

        <table>
            <tr>
                <td><h2 id="tdStoreName"></h2></td>
                <td ><h2 id="tdAll"></h2></td>
                <td><h2> @LangHelper.Get("Inventory_Label_Inventories")</h2></td>
            </tr>
        </table>
 
    <div style="width:100%;" align="right">
        <button class="btn btn-default" data-toggle="modal" data-target="#" id="invOutboundBtn">
            @LangHelper.Get("Delivery_Button_Outbound")
        </button>
        <button class="btn btn-default" data-toggle="modal" data-target="#" id="invInboundBtn">
            @LangHelper.Get("Delivery_Button_Inbound")
        </button>
        <button class="btn btn-default" data-toggle="modal" data-target="#" id="invExportBtn">
            @LangHelper.Get("Excel_Button_Export")
        </button>
        <button class="btn btn-default" data-toggle="modal"  data-target="#" id="invImportBtn">
            @LangHelper.Get("Excel_Button_Import")
        </button>
    </div>
    <table class="table table-striped display nowrap" id="invTable" cellspacing="0" >
        <thead>
            <tr>
                <th style="padding-left:10px!important"><input name="select_all" value="1" id="invTableSelectAllBox" type="checkbox"></th>
                <th>
                    @Html.DisplayNameFor(model => model.Product.SKU).ToString()
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Product.ShortTitle).ToString()
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Avail).ToString()
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.OnHold).ToString()
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.SwAvail).ToString()
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.OnIn).ToString()
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.OnOut).ToString()
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.InSum).ToString()
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.OutSum).ToString()
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.DiffSum).ToString()
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ShipMiss).ToString()
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Store.Name).ToString()
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Store.TypeLayout).ToString()
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.UpdateDateLayout).ToString()
                </th>
            </tr>
        </thead>
        <tbody></tbody>
    </table>
</div>

WHL/Views/Inventory/Query.cshtml
@Scripts.Render("~/Scripts/Common/laydate")
@Styles.Render("~/Styles/Common/laydate")

<!--Query Form-->
<form id="invQueryForm">
    <!--Inventory Stores Panel-->
    <div class="panel panel-success" >
        <div class="panel-heading text-success"><div align="left"><b>@LangHelper.Get("Inventory_Label_Stores")</b></div></div>
        <div class="panel-body">
            <div id="invQueryStoreDiv" style="min-height:120px;"></div>
            <input type="hidden" class="form-control" name="StoreID" id="invStoreID"/>
        </div>
    </div>


    <!--Iventory Query Panel-->
    <div class="panel panel-success">
        <div class="panel-heading text-success"><div align="left"><b>@LangHelper.Get("Inventory_Label_SearchTools")</b></div></div>
        <div class="panel-body">
            <div class="form-group">
                <label class="text-success">@LangHelper.Get("Product_Entity_ShortTitle")</label>
                <input type="text" class="form-control" name="Product.shortTitle" placeholder="Iphone">
            </div>
            <div class="form-group">
                <label class="text-success">@LangHelper.Get("Product_Entity_SKU")</label>
                <input type="text" class="form-control" name="Product.SKU" placeholder="A001">
            </div>
            <div class="form-group">
                <label class="text-success">@LangHelper.Get("Inventory_Entity_Avail")</label>
                <div style="width:100%">
                    <div style="float:left;width:45%;"><input type="text" class="form-control " name="QueryAvail1" placeholder="0" style=""></div>
                    <div style="float:left;width:8%;">&nbsp;&nbsp;&nbsp;</div>
                    <div style="float:left;width:45%;"><input type="text" class="form-control" name="QueryAvail2" placeholder="0" style=""></div>
                    <div style="clear:both"></div> 
                </div>
            </div>
            <div class="form-group">
                <label class="text-success">@LangHelper.Get("Base_Entity_UpdateDateLayout")</label>
                <input type="text" class="form-control" name="QUeryUpdateDate1" id="QueryUpdateTime1" placeholder="2016-01-01" onclick="laydate()">
                <br/>
                <input type="text" class="form-control" name="QUeryUpdateDate2" id="QueryUpdateTime2" placeholder="2016-12-31" onclick="laydate()">
            </div>
            <input type="button" onclick="invSearch()" class="btn btn-success" value="@LangHelper.Get("Common_Button_Search")" />
            <input type="button" onclick="invReset()" class="btn btn-toolbar" value="@LangHelper.Get("Common_Button_Reset")" />
        </div>
    </div>
</form>