WHL/Controllers/DeliveryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.IO;

using WHL.Models.Virtual;
using WHL.Models.Entity.Deliveries;

namespace WHL.Controllers
{
    /// <summary>
    /// DeliveryController：we put all delivery view controllers here
    /// </summary>
    public class DeliveryController : BaseController
    {

        /// <summary>
        /// Get the delivery list result in jquery data table JSON format, return the DataTable Result with paging and sorting.
        /// </summary>
        /// <param name="dtParams">Jquery Data Table Parameter</param>
        /// <param name="queryInventory">Query Delivery Object</param>
        /// <returns>JSON: DataTable Result with paging and sorting</returns>
        public JsonNetResult GetDeliveryDataTableJson(DTParams dtParams, Delivery queryDelivery)
        {
            DTResult<Delivery> deliveryDataTableResult = deliveryService.GetDeliveryDataTableResult(dtParams, queryDelivery);
            return new JsonNetResult(deliveryDataTableResult);
        }

        /// <summary>
        /// Save the outbound delivery submit,including create and update
        /// </summary>
        /// <param name="submitDelivery">delivery from UI post</param>
        /// <returns>Json package result</returns>
        public JsonNetResult OutboundSubmitDeliveryJson(Delivery submitDelivery)
        {
            JsonNetPackResult packResult = deliveryService.OutboundSubmitDelivery(submitDelivery);
            return new JsonNetResult(packResult);
        }

        /// <summary>
        /// Delete an outbound submited delivery.
        /// </summary>
        /// <param name="submitDelivery">delivery from UI post</param>
        /// <returns>Json package result</returns>
        public JsonNetResult OutboundDeleteDeliveryJson(Delivery submitDelivery)
        {
            JsonNetPackResult packResult = deliveryService.OutboundDeleteDelivery(submitDelivery);
            return new JsonNetResult(packResult);
        }

        /// <summary>
        /// Process an submited outbound delivery.
        /// </summary>
        /// <param name="submitDelivery">delivery from UI post</param>
        /// <returns>Json package result</returns>
        public JsonNetResult OutboundProcessDeliveryJson(Delivery submitDelivery)
        {
            JsonNetPackResult packResult = deliveryService.OutboundProcessDelivery(submitDelivery);
            return new JsonNetResult(packResult);
        }

        /// <summary>
        /// Cancel an outbound processing delivery.
        /// </summary>
        /// <param name="submitDelivery">delivery from UI post</param>
        /// <returns>Json package result</returns>
        public JsonNetResult OutboundCancelDeliveryJson(Delivery submitDelivery)
        {
            JsonNetPackResult packResult = deliveryService.OutboundCancelDelivery(submitDelivery);
            return new JsonNetResult(packResult);
        }

        /// <summary>
        /// Ship and outbound processing delivery
        /// </summary>
        /// <param name="submitDelivery">delivery from UI post</param>
        /// <returns>Json package result</returns>
        public JsonNetResult OutboundShipDeliveryJson(Delivery submitDelivery)
        {
            JsonNetPackResult packResult = deliveryService.OutboundShipDelivery(submitDelivery);
            return new JsonNetResult(packResult);
        }

        /// <summary>
        /// Save the inbound delivery submit,including create and update
        /// </summary>
        /// <param name="submitDelivery">delivery from UI post</param>
        /// <returns>Json package result</returns>
        public JsonNetResult InboundSubmitDeliveryJson(Delivery submitDelivery)
        {
            JsonNetPackResult packResult = deliveryService.InboundSubmitDelivery(submitDelivery);
            return new JsonNetResult(packResult);
        }

        /// <summary>
        /// Save the inbound delivery receive
        /// </summary>
        /// <param name="submitDelivery">delivery from UI post</param>
        /// <returns>Json package result</returns>
        public JsonNetResult InboundReceiveDeliveryJson(Delivery submitDelivery)
        {
            JsonNetPackResult packResult = deliveryService.InboundReceiveDeliveryJson(submitDelivery);
            return new JsonNetResult(packResult);
        }

        /// <summary>
        /// Delete an inbound submited delivery.
        /// </summary>
        /// <param name="submitDelivery">delivery from UI post</param>
        /// <returns>Json package result</returns>
        public JsonNetResult InboundDeleteDeliveryJson(Delivery submitDelivery)
        {
            JsonNetPackResult packResult = deliveryService.InboundDeleteDelivery(submitDelivery);
            return new JsonNetResult(packResult);
        }

        /// <summary>
        /// Finish an inbound submited delivery.
        /// </summary>
        /// <param name="submitDelivery">delivery from UI post</param>
        /// <returns>Json package result</returns>
        public JsonNetResult InboundFinishDeliveryJson(Delivery submitDelivery)
        {
            JsonNetPackResult packResult = deliveryService.InboundFinishDeliveryJson(submitDelivery);
            return new JsonNetResult(packResult);
        }


    }
}

WHL/Controllers/InventoryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.IO;
using System.Data.OleDb;

using WHL.Helpers;
using WHL.Services;

using WHL.Models.Virtual;
using WHL.Models.Entity.Inventories;
using WHL.Models.Entity.FileDatas;

namespace WHL.Controllers
{
    /// <summary>
    /// InventoryController：we put all inventory view controllers here
    /// </summary>
    public class InventoryController : BaseController
    {


        /// <summary>
        /// Query partial view page
        /// </summary>
        /// <returns></returns>
        public ActionResult Query()
        {
            
            return PartialView();
        }

        /// <summary>
        /// List partial view page
        /// </summary>
        /// <returns></returns>
        public ActionResult List()
        {
            return PartialView();
        }


        /// <summary>
        /// Get the inventory list result in jquery data table JSON format, return the DataTable Result with paging and sorting.
        /// </summary>
        /// <param name="dtParams">Jquery Data Table Parameter</param>
        /// <param name="queryInventory">Query Inventory Object</param>
        /// <returns>JSON: DataTable Result with paging and sorting</returns>
        public JsonNetResult GetInventoryDataTableJson(DTParams dtParams, Inventory queryInventory)
        {
            DTResult<Inventory> inventoryDataTableResult = inventoryService.GetInventoryDataTableResult(dtParams, queryInventory);
            return new JsonNetResult(inventoryDataTableResult);
        }


        // EXPORT: Export Inventory List
        public JsonNetResult ExportJson(FileData submitFileData,Inventory eff)
        {
            JsonNetPackResult packResult = null;
            packResult = inventoryService.Export(submitFileData, eff);
            return new JsonNetResult(packResult);
        }

        /// <summary>
        /// Json upload an excel file and import to db
        /// </summary>
        /// <param name="uploadFile">the excel upload file</param>
        /// <param name="mapRule">the map rule of import</param>
        /// <returns></returns>
        public JsonNetResult ImportJson(FileData submitFileData, int eff)
        {
            JsonNetPackResult packResult = inventoryService.Import(submitFileData,eff);
            return new JsonNetResult(packResult);
        }

        /// <summary>
        /// close the database
        /// </summary>
        /// <param name="disposing"></param>
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                inventoryService.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WHL/Controllers/MapRuleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using WHL.Services;
using WHL.Models.Virtual;
using WHL.Models.Entity.FileDatas;
using WHL.Models.Entity.MapRules;


namespace WHL.Controllers
{
    /// <summary>
    /// MapRuleController：we put all mapping rule view controllers here
    /// </summary>
    public class MapRuleController : BaseController
    {

        /// <summary>
        /// Get the mapRule list result in jquery data table JSON format, return the DataTable Result with paging and sorting.
        /// </summary>
        /// <param name="dtParams">Jquery Data Table Parameter</param>
        /// <param name="queryInventory">Query Inventory Object</param>
        /// <returns>JSON: DataTable Result with paging and sorting</returns>
        public JsonNetResult GetMapRuleDataTableJson(DTParams dtParams, MapRule queryMapRule)
        {
            DTResult<MapRule> mapRuleDataTableResult = mapRuleService.GetMapRuleDataTableResult(dtParams, queryMapRule);
            return new JsonNetResult(mapRuleDataTableResult);
        }


        /// <summary>
        /// get all mapping rules options.
        /// </summary>
        /// <returns>Json: map rule options List</returns>
        public JsonNetResult GetMapRuleOptionListJson(MapRuleOption queryMapRuleOption)
        {
            List<MapRuleOption> mapRuleOptionDataList = mapRuleService.GetMapRuleOptionDataList(queryMapRuleOption);
            return new JsonNetResult(mapRuleOptionDataList);
        }

      
    }
}

WHL/Controllers/StoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using WHL.Services;
using WHL.Models.Virtual;
using WHL.Models.Entity.Stores;

namespace WHL.Controllers
{
    /// <summary>
    /// StoreController：we put all store view controllers here
    /// </summary>
    public class StoreController : BaseController
    {
        /// <summary>
        /// Get the store list result in jquery data table JSON format, return the DataTable Result with paging and sorting.
        /// </summary>
        /// <param name="dtParams">Jquery Data Table Parameter</param>
        /// <param name="queryInventory">Query Store Object</param>
        /// <returns>JSON: DataTable Result with paging and sorting</returns>
        public JsonNetResult GetStoreDataTableJson(DTParams dtParams, Store queryStore)
        {
            DTResult<Store> storeDataTableResult = storeService.GetStoreDataTableResult(dtParams, queryStore);
            return new JsonNetResult(storeDataTableResult);
        }
    }
}

WHL/Views/Shared/Header.cshtml
@{Employee currentEmployee = (Employee)@Session["CurrentEmployee"];}
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Warehouse and Logitics Modules</title>
@Scripts.Render("~/Scripts/Common/modernizr")
@Scripts.Render("~/Scripts/Common/jquery")

@Scripts.Render("~/Scripts/Common/bootstrap")
@Scripts.Render("~/Scripts/Common/tools")

@Styles.Render("~/Styles/Common/bootstrap")

<script>
    // set the default lang
    var defaultLang = "@LangHelper.GetThreadLang()";
    // generate the javascript language resource!
    @Html.Raw(LangHelper.GenerateJsResource());
</script>


<script>
    // generate all enum javascript resources in entities.
    @Html.Raw(BaseEntity.GenerateJsEnumResource());
</script>

<script>
// 我们在这里定义一个全局的变量，放session employee
var currentEmployee = {
    ID:     "@currentEmployee.ID",
    Name:   "@currentEmployee.Name",
    ClientID: "@currentEmployee.ClientID"
}


//定义一个全局的变量 用于全局设置DataTable 多语言
var dtLanguage = {
    lengthMenu: Common_DataTable_Label_lengthMenu ,
    zeroRecords:  Common_DataTable_Label_zeroRecords ,
    info:  Common_DataTable_Label_info ,
    infoEmpty: Common_DataTable_Label_infoEmpty ,
    infoFiltered: Common_DataTable_Label_infoFiltered ,
    paginate: {
        first:  Common_DataTable_Label_paginate_first ,
        last:  Common_DataTable_Label_paginate_last,
        next:  Common_DataTable_Label_paginate_next ,
        previous: Common_DataTable_Label_paginate_previous ,
    }
}
</script>

WHL/Views/Shared/Menu.cshtml
@{Employee currentEmployee = (Employee)@Session["CurrentEmployee"];}
@Scripts.Render("~/Scripts/WHL/menu")
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-header" style="width:30%!important;">
        @Html.ActionLink("IChannel Warehouse and Logistics", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })

    </div>
    <div style="width: 60% !important; float: right; vertical-align: middle; " align="right">
        <ul class="nav navbar-nav" style="float:right!important;">
            <li>@Html.ActionLink(@LangHelper.Get("Menu_Label_Home"), "Index", "Home")</li>
            <li>@Html.ActionLink(@LangHelper.Get("Menu_Label_Inventory"), "Index", "Inventory")</li>
            <li>@Html.ActionLink(@LangHelper.Get("Menu_Label_Delivery"), "Index", "Delivery")</li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    @LangHelper.Get("Menu_Label_Setting")<b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    <li>@Html.ActionLink(@LangHelper.Get("Menu_Label_Store"), "Index", "Store")</li>
                    <li>@Html.ActionLink(@LangHelper.Get("Menu_Label_MapRule"), "Index", "MapRule")</li>
                </ul>
            </li>  

            <li>@Html.ActionLink(@LangHelper.Get("Menu_Label_Log"), "Index", "Log")</li>
            <li>@Html.ActionLink(@LangHelper.Get("Menu_Label_Employee")+ ":  " + currentEmployee.Name, "Index", "Home")</li>
            <li>&nbsp;</li>
            <li style="padding-top:15px;padding-bottom:15px;">
                <select id="langSelect" onchange="switchLang(this.value)">
                    <option value="zh_CN">简体中文</option>
                    <option value="zh_HK">繁体中文</option>
                    <option value="en_US">English</option>
                    <option value="th_TH">ภาษาไทย</option>
                </select>
            </li>
            <li>&nbsp;</li>
        </ul>
    </div>


</div>

WHL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    @{Html.RenderAction("Header");}
</head>
<body>
    @{Html.RenderAction("Menu");}
    @RenderBody()
</body>
</html>